// Registered institutions from Annex A (Acquirer ID) of the Bangladesh Bank P2P specification,
// docs/bb-banglaqr-p2p-specification.md in rvl-secure-bqr-manager. Static until the API serves this list.
// Institution code = type (Tag 26.01) + institution ID (Tag 26.02). NBFIs (01) are not in Annex A.
export type RegistryEntry = { name: string; type: string; id: string }

export const institutionRegistry: RegistryEntry[] = [
  { name: "Agrani Bank PLC", type: '00', id: '0010' },
  { name: "Al-Arafah Islami Bank PLC.", type: '00', id: '0015' },
  { name: "Ab Bank PLC.", type: '00', id: '0020' },
  { name: "Bangladesh Commerce Bank PLC.", type: '00', id: '0030' },
  { name: "Bangladesh Krishi Bank", type: '00', id: '0035' },
  { name: "Bangladesh Samabaya Bank PLC.", type: '00', id: '0040' },
  { name: "Bangladesh Dev. Bank PLC.", type: '00', id: '0047' },
  { name: "Basic Bank PLC.", type: '00', id: '0055' },
  { name: "Brac Bank PLC.", type: '00', id: '0060' },
  { name: "Bank Al-Falah PLC", type: '00', id: '0065' },
  { name: "Bank Asia PLC.", type: '00', id: '0070' },
  { name: "Citi Bank N. A.", type: '00', id: '0075' },
  { name: "Commercial Bank Of Ceylon", type: '00', id: '0080' },
  { name: "Dhaka Bank PLC.", type: '00', id: '0085' },
  { name: "Dutch-Bangla Bank PLC", type: '00', id: '0090' },
  { name: "Eastern Bank PLC.", type: '00', id: '0095' },
  { name: "Exim Bank PLC.", type: '00', id: '0100' },
  { name: "First Security Islami Bank PLC", type: '00', id: '0105' },
  { name: "Habib Bank PLC.", type: '00', id: '0110' },
  { name: "The Hong Kong And Shanghai Banking Corporation Ltd.", type: '00', id: '0115' },
  { name: "Ific Bank PLC.", type: '00', id: '0120' },
  { name: "Islami Bank Bangladesh PLC.", type: '00', id: '0125' },
  { name: "Jamuna Bank PLC.", type: '00', id: '0130' },
  { name: "Janata Bank PLC.", type: '00', id: '0135' },
  { name: "Mercantile Bank PLC.", type: '00', id: '0140' },
  { name: "Mutual Trust Bank PLC.", type: '00', id: '0145' },
  { name: "National Bank PLC.", type: '00', id: '0150' },
  { name: "National Bank Of Pakistan", type: '00', id: '0155' },
  { name: "National Credit & Commerce Bank PLC.", type: '00', id: '0160' },
  { name: "One Bank PLC.", type: '00', id: '0165' },
  { name: "Prime Bank PLC.", type: '00', id: '0170' },
  { name: "Pubali Bank PLC.", type: '00', id: '0175' },
  { name: "Rajshahi Krishi Unnayan Bank", type: '00', id: '0180' },
  { name: "Rupali Bank PLC.", type: '00', id: '0185' },
  { name: "Shahjalal Islami Bank PLC.", type: '00', id: '0190' },
  { name: "Social Islami Bank PLC", type: '00', id: '0195' },
  { name: "Sonali Bank PLC.", type: '00', id: '0200' },
  { name: "Southeast Bank PLC.", type: '00', id: '0205' },
  { name: "Standard Bank PLC.", type: '00', id: '0210' },
  { name: "Standard Chartered Bank", type: '00', id: '0215' },
  { name: "State Bank Of India", type: '00', id: '0220' },
  { name: "The City Bank PLC.", type: '00', id: '0225' },
  { name: "Icb Islamic Bank Ltd.", type: '00', id: '0230' },
  { name: "The Premier Bank PLC.", type: '00', id: '0235' },
  { name: "Trust Bank PLC.", type: '00', id: '0240' },
  { name: "United Commercial Bank Limited", type: '00', id: '0245' },
  { name: "Uttara Bank PLC.", type: '00', id: '0250' },
  { name: "Woori Bank", type: '00', id: '0255' },
  { name: "Nrb Commercial Bank PLC.", type: '00', id: '0260' },
  { name: "Union Bank PLC.", type: '00', id: '0265' },
  { name: "Sbac Bank PLC.", type: '00', id: '0270' },
  { name: "Meghna Bank PLC.", type: '00', id: '0275' },
  { name: "Padma Bank PLC.", type: '00', id: '0280' },
  { name: "Midland Bank PLC.", type: '00', id: '0285' },
  { name: "Nrb Bank PLC.", type: '00', id: '0290' },
  { name: "Modhumoti Bank PLC.", type: '00', id: '0295' },
  { name: "Global Islami Bank PLC.", type: '00', id: '0300' },
  { name: "Shimanto Bank Limited", type: '00', id: '0305' },
  { name: "Community Bank Bangladesh PLC.", type: '00', id: '0310' },
  { name: "Bengal Commercial Bank", type: '00', id: '0315' },
  { name: "Citizens Bank Plc", type: '00', id: '0320' },
  { name: "iPay Systems Limited", type: '03', id: '1001' },
  { name: "Dmoney Bangladesh Limited", type: '03', id: '1002' },
  { name: "Recursion FinTech Limited (Cash Baba)", type: '03', id: '1003' },
  { name: "Green & Red Technologies Ltd.", type: '03', id: '1004' },
  { name: "Progoti Systems Ltd.", type: '03', id: '1005' },
  { name: "Sheba Fintech Limited.", type: '03', id: '1006' },
  { name: "ABG Technologies Limited (Pocket)", type: '03', id: '1007' },
  { name: "Digital Payments Limited (Pathao Pay)", type: '03', id: '1008' },
  { name: "Shamadhan Services Limited", type: '03', id: '1009' },
  { name: "ROCKET", type: '02', id: '2001' },
  { name: "bKash", type: '02', id: '2002' },
  { name: "Islami Bank mCash", type: '02', id: '2003' },
  { name: "Trust Axiata Pay (TAP)", type: '02', id: '2004' },
  { name: "UPAY", type: '02', id: '2005' },
  { name: "Rupali Bank SureCash", type: '02', id: '2006' },
  { name: "Islamic Wallet", type: '02', id: '2007' },
  { name: "OK Wallet", type: '02', id: '2008' },
  { name: "MYCash", type: '02', id: '2009' },
  { name: "FSIBL FirstPay SureCash", type: '02', id: '2010' },
  { name: "TeleCash", type: '02', id: '2011' },
  { name: "MeghnaPay", type: '02', id: '2012' },
  { name: "Nagad", type: '02', id: '2013' },
  { name: "Prime Bank FinTech Limited", type: '02', id: '2014' },
  { name: "IT Consultants Ltd.", type: '04', id: '3001' },
  { name: "Software Shop Limited", type: '04', id: '3002' },
  { name: "ShurjoMukhi Ltd.", type: '04', id: '3003' },
  { name: "Portonics Limited", type: '04', id: '3004' },
  { name: "Walletmix Limited", type: '04', id: '3005' },
  { name: "Soft Tech Innovation Limited", type: '04', id: '3006' },
  { name: "DGePay Services Limited", type: '05', id: '4001' },
  { name: "SSLCOMMERZ Limited", type: '05', id: '4002' },
  { name: "Zaytoon FinTech Limited", type: '05', id: '4003' },
]
